theme : minima
title: Learn About Me
author: By : Nyssa Gandhi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is Nyssa. I'm 15 years old and am a Sophomore at East Brunswick High School. 
  I like to spend my free time playing video games, coding, or drawing. I like to 
  create animations and eat new foods as well.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Ooftaco # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
