theme: minima
title: About Me
author: By Nyssa Gandhi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is Nyssa, I am 15 years old and am a Sophomore at East Brunswick Highschool.
  I spend my free time playing games, coding, and drawing/animating. I like to talk to other 
  people and share my drawings online.

# social links
instagram_username: _cyph3r_ # DO NOT include the @ character, or else the build will fail!
github_username:  ooftaco # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
